databaseChangeLog:
  - changeSet:
      id: 1.0.0-1
      author: liquibase-generator
      changes:
        - createTable:
            tableName: account
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: first_name
                  type: varchar(255)
              - column:
                  name: last_name
                  type: varchar(255)
              - column:
                  name: email
                  type: varchar(255)
              - column:
                  name: password
                  type: varchar(255)
              - column:
                  name: phone
                  type: varchar(255)
              - column:
                  name: photo
                  type: varchar(255)
              - column:
                  name: profile_cover
                  type: varchar(255)
              - column:
                  name: about
                  type: varchar(255)
              - column:
                  name: city
                  type: varchar(255)
              - column:
                  name: country
                  type: varchar(255)
              - column:
                  name: status_code
                  type: varchar(255)
              - column:
                  name: reg_date
                  type: timestamp
              - column:
                  name: birth_date
                  type: timestamp
              - column:
                  name: message_permission
                  type: varchar(255)
              - column:
                  name: last_online_time
                  type: timestamp
              - column:
                  name: emoji_status
                  type: varchar(255)
              - column:
                  name: created_on
                  type: timestamp
              - column:
                  name: updated_on
                  type: timestamp
              - column:
                  name: deletion_timestamp
                  type: timestamp
              - column:
                  name: deleted
                  type: boolean
              - column:
                  name: blocked
                  type: boolean
              - column:
                  name: is_online
                  type: boolean