server:
  port: 8082

app:
  kafka:
    kafkaUpdateUserTopic: "update_user_topic"
    kafkaRegisterTopic: "REGISTER_TOP"
    kafkaMessageGroupId: "kafka-message-group-id"
  integration:
    auth-url: http://localhost:8080

spring:
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:config/liquibase/master.yml
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1gjAVnJ}
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
  kafka:
    bootstrap-servers: localhost:9092
