server:
  port: 8082

app:
  kafka:
    kafkaUpdateUserTopic: "update_user_topic"
    kafkaRegisterTopic: "REGISTER_TOP"
    kafkaMessageGroupId: "kafka-message-group-id"
  integration:
    auth-url: ${TOKEN_VALIDATION_URL:http://localhost:8080}

spring:
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:config/liquibase/master.yml
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1gjAVnJ}
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
  kafka:
    bootstrap-servers: ${EVENTKAFKA_BOOTSTRAP-SERVERS:localhost:9092}
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
